export const ADD_CONTACT = "ADD_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const SEARCH_CONTACT = "SEARCH_CONTACT"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"